### ISSUE TITLE
This repo is awesome!

### ISSUE THREAD

**Issue by andrewjong** [ashleve/lightning-hydra-template#102] opened 2021-03-17 20:26 UTC
Hey @hobogalaxy , this template/boilerplate is spectacular! It's exactly what I've been looking for for the past couple of years. No issues to report, just wanted to say keep up the good work :) Thanks so much for your useful contribution.

**Comment by hobogalaxy** [comment] 2021-03-18 09:43
Hi @andrewjong, thank you for using it! 
Beware this is still work in progress and it's based on development version of hydra, so not everything works perfectly right now. 
I've already run into fair amount of bugs. 

I'm still figuring out best practices and clean ways to do some things. You can expect the template to become more polished in the coming month.

**Comment by LuoXin-s** [comment] 2021-03-18 11:10
Hi @hobogalaxy, what about the bugs you mean here? I'm reproducing a project using this template.

**Comment by hobogalaxy** [comment] 2021-03-18 11:35
@LuoXin-s watch out  for things that you try to return from step methods in LightningModule, like in [this line](https://github.com/hobogalaxy/lightning-hydra-template/blob/6bf03035107e12568e3e576e82f83da0f91d6a11/src/models/mnist_model.py#L74) -  it sometimes behaves weirdly, especially when trying to use `trainer.callback_metrics` attribute at the same time. I have yet to investigate it and report to lightning team.

If you keep your project similar to mnist example than you probably won't run into any issues.

I also had this weird issue with [this arg from optimizer configuration](https://github.com/hobogalaxy/lightning-hydra-template/blob/6bf03035107e12568e3e576e82f83da0f91d6a11/configs/optimizer/adam.yaml#L8), using it simply crashes the run for me. 

Also, installing hydra tab completion is not working for me, but that's probably because of using development version.

**Comment by LuoXin-s** [comment] 2021-03-18 11:40
@hobogalaxy Thank you for your valuable reply. Unfortunately, my project is not simiar to mnist, I'll carefully test it to see if there are any problems and share to you.

**Comment by hobogalaxy** [comment] 2021-03-22 00:03
@LuoXin-s 
Quick update on bugs.

The problem with optimizer argument is fixed now. Turns out when instantiating some objects you need to add _partial_ parameter. You can see it [here](https://github.com/hobogalaxy/lightning-hydra-template/blob/main/configs/optimizer/adam.yaml). I also added _partial_ to trainer [here](https://github.com/hobogalaxy/lightning-hydra-template/blob/755cd89cf096575bb199c26de913ca405be16644/src/train.py#L62) because without it some things break, like stochastic weight averaging flag.

Tab completion is also no longer an issue for me, it seems to work as intended.

As for problems with returning values from step method, I made an issue about it here: https://github.com/PyTorchLightning/pytorch-lightning/issues/6614

Currently I haven't found any more issues with the template.

**Comment by RomanShen** [comment] 2021-05-07 11:04
Great job! Thanks a lot!

**Closed** 2022-04-18 11:50 UTC
