### ISSUE TITLE
Assign stage flag from `train.yaml`

### ISSUE THREAD

**Issue by abhijeetdhakane** [ashleve/lightning-hydra-template#469] opened 2022-11-23 19:06 UTC
There is a ` def setup(self, stage: Optional[str] = None):` `stage` flag in the `datamodule`, will it be possible to initiate stage -> train or stage-> test from `train.yaml` 
If look in `train.yaml`
```
# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True
```
Just to save memory

**Comment by ashleve** [comment] 2023-02-10 22:48
Not sure what the issue is about. The datamodule stage flag is usually provided by lightning to indicate the current phase (train/validate/test). Would you like to control it directly?

Closing this for now. Feel free to reopen if you still have the problem.

**Closed by ashleve** 2023-02-10 22:48 UTC
Labels: question
