### ISSUE TITLE
"You must import Comet before these modules: keras, tensorboard, tensorflow, torch"

### ISSUE THREAD

**Issue by Ir1d** [ashleve/lightning-hydra-template#217] opened 2021-12-10 04:48 UTC
Hi,

I'm running the `python run.py` with comet logger enabled, and I'm getting this error.

**Comment by Ir1d** [comment] 2021-12-10 05:10
The problem is not critical, because I can add `import comet_ml` to the beginning of `run.py` to get rid of this.

**Comment by ashleve** [comment] 2021-12-13 14:54
Thanks for reporting. I think we won't be adding the `comet_ml` import since the problem is easy to understand and resolve for anyone who stumbles upon it, and I would prefer for the template to be logger agnostic and don't require any logger to be installed by default (I know the template currently has some wandb integration by default but this will be probably changed in the near future).

**Closed** 2021-12-13 16:04 UTC
